sudo: false

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - mongodb

install:
  - pip install -r test_requirements.txt
  - pip install -e .

script:
  - py.test

after_success:
  - codecov --token=e854bba4-8a64-4486-b4b5-faeb08368841
