sudo: false

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - mongodb

install:
  - pip install -r test_requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - py.test

after_success:
  - codecov --token=e854bba4-8a64-4486-b4b5-faeb08368841
