language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install pytest-cov

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - py.test --cov=dark_keeper

after_success:
  - coveralls
