language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - mongodb

install:
  - pip install -r test_requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - py.test --cov=dark_keeper

after_success:
  - coveralls
